---
- name: Check that the somefile.conf exists
  ansible.builtin.stat:
    path: {{ ansible_user_dir }}/.ideavimrc
  register: ideavimrc_file

- name: "{{ role_name }} | Create symlink to .ideavim"
  ansible.builtin.command: "ln -s {{ role_path }}/files/.ideavimrc {{ ansible_user_dir }}"
  changed_when: false
  when: not ideavimrc_file.stat.exists

