---
- name: "{{ role_name }} | MacOSX | Install yabai"
  community.general.homebrew:
    name: koekeishiya/formulae/yabai
    state: present

- name: "{{ role_name }} | MacOSX | Create yabai Config Directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/yabai"
    mode: "0755"
    state: directory

- name: "{{ role_name }} | MacOSX | Deploy yabai Config"
  ansible.builtin.copy:
    src: "yabairc"
    dest: "{{ ansible_user_dir }}/.config/yabai/yabairc"
    mode: "0644"

- name: "{{ role_name }} | MacOSX | Stop yabai"
  ansible.builtin.command: yabai --stop-service
  ignore_errors: true
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: "{{ role_name }} | MacOSX | Start yabai"
  ansible.builtin.command: yabai --start-service
