---
- name: "yabai | MacOSX | Install yabai"
  community.general.homebrew:
    name: koekeishiya/formulae/yabai
    state: present

- name: "yabai | MacOSX | Create yabai Config Directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/yabai"
    mode: "0755"
    state: directory

- name: "yabai | MacOSX | Deploy yabai Config"
  ansible.builtin.copy:
    src: "yabairc"
    dest: "{{ ansible_user_dir }}/.config/yabai/yabairc"
    mode: "0644"

