---
- name: "{{ role_name }} | MacOSX | Install yazi"
  community.general.homebrew:
    name: yazi
    state: present

- name: "{{ role_name }} | MacOSX | Install optional dependencies"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - ffmpeg
    - sevenzip
    - jq
    - poppler
    - fd
    - ripgrep
    - fzf
    - zoxide
    - imagemagick
    - font-symbols-only-nerd-font

- name: "{{ role_name }} | MacOSX | Ensure .config/yazi exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/yazi"
    mode: "0755"
    state: directory

- name: "{{ role_name }} | MacOSX | Deploy yazi config"
  ansible.builtin.copy:
    src: "yazi.toml"
    dest: "{{ ansible_user_dir }}/.config/yazi/yazi.toml"
    mode: "0644"

- name: "{{ role_name }} | MacOSX | Deploy yazi keymap"
  ansible.builtin.copy:
    src: "keymap.toml"
    dest: "{{ ansible_user_dir }}/.config/yazi/keymap.toml"
    mode: "0644"

- name: "{{ role_name }} | MacOSX | Deploy yazi theme"
  ansible.builtin.copy:
    src: "theme.toml"
    dest: "{{ ansible_user_dir }}/.config/yazi/theme.toml"
    mode: "0644"

- name: "{{ role_name }} | MacOSX | Setting theme to check/download"
  ansible.builtin.set_fact:
    yazi_theme: catppuccin-mocha

- name: "{{ role_name }} | Check if {{ yazi_theme }} exists"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/yazi/flavors/{{ yazi_theme }}.yazi"
  register: yazi_theme_dir

- name: "{{ role_name }} | Deleting {{ yazi_theme }}"
  ansible.builtin.command: "rm -rf {{ ansible_user_dir }}/.config/yazi/flavors/{{ yazi_theme }}.yazi"
  when: yazi_theme_dir.stat.exists

- name: "{{ role_name }} | MacOSX | Download theme"
  ansible.builtin.command: "ya pack -a yazi-rs/flavors:{{ yazi_theme }}"
