---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Check if .zshrc file exists"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc_file

- name: "{{ role_name }} | Deleting .zshrc"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: absent
  when: zshrc_file.stat.exists

- name: "{{ role_name }} | Create symlink to .zshrc"
  ansible.builtin.command: "ln -s {{ role_path }}/files/.zshrc {{ ansible_user_dir }}"
  changed_when: false

- name: "{{ role_name }} | Copy custom zsh config"
  ansible.builtin.copy:
    src: "zsh"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
