---
- name: "{{ role_name }} | MacOSX | Install kitty"
  community.general.homebrew_cask:
    name: kitty
    state: present

- name: "{{ role_name }} | MacOSX | Deploy Kitty Config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    mode: "0755"
    state: directory

- name: "{{ role_name }} | MacOSX | Setting Base Kitty Config"
  ansible.builtin.set_fact:
    kitty_config: kitty.conf

- name: "{{ role_name }} | MacOSX | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/kitty_{{ ansible_distribution }}.conf"
  register: kitty_distribution_config

- name: "{{ role_name }} | MacOSX | Found, Setting Kitty Config: kitty_{{ ansible_distribution }}.conf"
  ansible.builtin.set_fact:
    kitty_config: "kitty_{{ ansible_distribution }}.conf"
  when: kitty_distribution_config.stat.exists

- name: "{{ role_name }} | MacOSX | Deploy Kitty Config: {{ kitty_config }}"
  ansible.builtin.copy:
    src: "{{ kitty_config }}"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    mode: "0644"

- name: "{{ role_name }} | MacOSX | Deploy Kitty Theme"
  ansible.builtin.copy:
    src: "mocha.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/mocha.conf"
    mode: "0644"
