---
- name: "{{ role_name }} | MacOSX | Install ghostty"
  community.general.homebrew_cask:
    name: ghostty
    state: present

- name: "{{ role_name }} | MacOSX | Ensure .config/ghostty exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/ghostty"
    mode: "0755"
    state: directory

- name: "{{ role_name }} | MacOSX | Deploy ghostty Config"
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/ghostty/config"
    mode: "0644"

