---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure ~/.config/lsd exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/lsd"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Copy lsd config"
  ansible.builtin.copy:
    src: "config.yml"
    dest: "{{ ansible_user_dir }}/.config/lsd/config.yml"
    mode: "0644"

- name: "{{ role_name }} | Copy colors.yaml"
  ansible.builtin.copy:
    src: "colors.yml"
    dest: "{{ ansible_user_dir }}/.config/lsd/colors.yml"
    mode: "0644"
