---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Install fd"
  community.general.homebrew:
    name: fd
    state: present

- name: "{{ role_name }} | Create fd Config Directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fd"
    mode: "0755"
    state: directory

- name: "{{ role_name }} | Deploy fd Config"
  ansible.builtin.copy:
    src: "ignore"
    dest: "{{ ansible_user_dir }}/.config/fd/ignore"
    mode: "0644"
