---
- name: "{{ role_name }} | MacOSX | Dependencies"
  community.general.homebrew:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - luarocks
      - rustup
      - chafa
    state: present

- name: "{{ role_name }} | MacOSX | Install"
  community.general.homebrew:
    name: neovim
    state: present

- name: "{{ role_name }} | MacOSX | Install cargo"
  ansible.builtin.command: "rustup-init -y"
